name: Analysis

on:
  push:
  pull_request:

jobs:
  analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: install dependency
        run: go install golang.org/x/lint/golint@latest
      - name: v1
        run: |
          cd v1
          golint ./...
          go vet ./...
      - name: v2
        run: |
          cd v2
          golint ./...
          go vet ./...