name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - '1.17'
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: v1
        run: cd v1 && go test ./... -race -coverprofile=coverage.txt -covermode=atomic
      - name: v2
        run: cd v2 && go test ./... -race -coverprofile=coverage.txt -covermode=atomic
      - uses: codecov/codecov-action@v2.1.0
        with:
          files: v1/coverage.txt,v2/coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
