name: Test

on:
  push:
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17' ]
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: test
        run: |
          go test ./... -race
          cd v2
          go test ./... -race
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: test
        run: |
          go test ./... -coverprofile=coverage.txt -covermode=atomic
          cd v2
          go test ./... -coverprofile=coverage.txt -covermode=atomic
      - uses: codecov/codecov-action@v2.1.0
        with:
          files: ./coverage.txt,v2/coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
